export const getData =
  [
    {
      "contents_id":1,
      "contents_detail_id":1,
      "contents_img":"../assets/img/001.jpg",
      "contents_name":"Question1",
      "contents_startment":"aaaaa",
      "contents_customer":"株式会社A",
      "choice1":"氏名",
      "choice2":"電話番号",
      "choice3":"住所",
      "choice4":"勤務先",
      "answer":3
    },
    {
      "contents_id":1,
      "contents_detail_id":2,
      "contents_img":"../assets/img/002.jpg",
      "contents_name":"Question2",
      "contents_startment":"bbbbb",
      "contents_customer":"株式会社B",
      "choice1":"名前",
      "choice2":"FAX番号",
      "choice3":"郵便番号",
      "choice4":"職場",
      "answer":3
    },
    {
      "contents_id":1,
      "contents_detail_id":3,
      "contents_img":"../assets/img/003.jpg",
      "contents_name":"Question3",
      "contents_startment":"ccccc",
      "contents_customer":"株式会社C",
      "choice1":"氏名",
      "choice2":"電話番号",
      "choice3":"住所",
      "choice4":"勤務先",
      "answer":3
    },
    {
      "contents_id":1,
      "contents_detail_id":4,
      "contents_img":"../assets/img/004.jpg",
      "contents_name":"Question4",
      "contents_startment":"ddddd",
      "contents_customer":"株式会社D",
      "choice1":"氏名",
      "choice2":"電話番号",
      "choice3":"住所",
      "choice4":"勤務先",
      "answer":3
    },
    {
      "contents_id":1,
      "contents_detail_id":5,
      "contents_img":"../assets/img/005.jpg",
      "contents_name":"Question5",
      "contents_startment":"eeeee",
      "contents_customer":"株式会社E",
      "choice1":"氏名",
      "choice2":"電話番号",
      "choice3":"住所",
      "choice4":"勤務先",
      "answer":3
    }
  ];