export const getData =
  [
    {
      "contents_id":1,
      "contents_name":require("../Assets/img/001.jpg"),
      "contents_type":1,
      "target_user":"a",
    },
    {
      "contents_id":2, 
      "contents_name":require("../Assets/img/002.jpg"),
      "contents_type":2,
      "target_user":"a",
    },
    {
      "contents_id":3,
      "contents_name":require("../Assets/img/003.jpg"),
      "contents_type":3,
      "target_user":"a",
    },
    {
      "contents_id":4,
      "contents_name":require("../Assets/img/004.jpg"),
      "contents_type":4,
      "target_user":"a",
    },
    {
      "contents_id":5, 
      "contents_name":require("../Assets/img/005.jpg"),
      "contents_type":5,
      "target_user":"a",
    }
  ];