export const getData =
  [
    {
      "contents_id":1,
      "contents_name":"確認問題1",
      "contents_type":2,
      "target_user":1,
    },
    {
      "contents_id":2,
      "contents_name":"確認問題2",
      "contents_type":2,
      "target_user":2,
    },
    {
      "contents_id":3,
      "contents_name":"確認問題3",
      "contents_type":2,
      "target_user":3,
    },
    {
      "contents_id":4,
      "contents_name":"スライド1",
      "contents_type":1,
      "target_user":1,
    },
    {
      "contents_id":5,
      "contents_name":"確認問題4",
      "contents_type":2,
      "target_user":2,
    },
    {
      "contents_id":6,
      "contents_name":"確認問題5",
      "contents_type":2,
      "target_user":3,
    },
    
  ];