export const getData =
[
    {
        "contents_id":1,
        "contents_detail_id":1,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":1
     },
     {
        "contents_id":1,
        "contents_detail_id":2,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":2
    },
    {
        "contents_id":1,
        "contents_detail_id":3,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":3
    },
    {
        "contents_id":1,
        "contents_detail_id":4,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":4
    },
    {
        "contents_id":1,
        "contents_detail_id":5,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":1
    },
    {
        "contents_id":1,
        "contents_detail_id":6,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":2
    },
    {
        "contents_id":1,
        "contents_detail_id":7,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":3
    },
    {
        "contents_id":1,
        "contents_detail_id":8,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":4
    },
    {
        "contents_id":1,
        "contents_detail_id":9,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":1
    },
    {
        "contents_id":1,
        "contents_detail_id":10,
        "contents_name":"あああ",
        "contents_statement":"Q1.個人情報とは何を指すか。下記の4つの内から選びなさい。!!!!!!!!!",
        "choice1":"氏名",
        "choice2":"電話番号",
        "choice3":"住所",
        "choice4":"勤務先",
        "answer":2
    }

];