export const getData =
  [
    {
      "user_id":1,
      "user_name":"testuser",
      "CurriculumName":"スライド①",
      "TestName":"確認問題①",
    },
    {
      "user_id":2,
      "user_name":"testuser2",
      "CurriculumName":"スライド②",
      "TestName":"確認問題②",
    },
    {
      "user_id":3,
      "user_name":"testuser3",
      "CurriculumName":"スライド③",
      "TestName":"確認問題③",
    }
  ];
