export const getContentsData =
[
    {
        "contents_id":1,
        "contents_name":"スライド①",
        "contents_type":1,
        "target_user":1,
    },
    {
        "contents_id":2,
        "contents_name":"スライド②",
        "contents_type":1,
        "target_user":2,
    },
    {
        "contents_id":3,
        "contents_name":"確認問題①",
        "contents_type":2,
        "target_user":1,
    },
    {
        "contents_id":4,
        "contents_name":"確認問題②",
        "contents_type":2,
        "target_user":2,
    },
];