export const getData =
  [
    {
      "CustomerID":1,
      "CustomerName":"testuser",
      "CurriculumName":"スライド①",
      "TestName":"確認問題①",
    },
    {
      "CustomerID":2,
      "CustomerName":"testuser2",
      "CurriculumName":"スライド②",
      "TestName":"確認問題②",
    },
    {
      "CustomerID":3,
      "CustomerName":"testuser3",
      "CurriculumName":"スライド③",
      "TestName":"確認問題③",
    }
  ];
